### ISSUE TITLE
Consider using mp4-merge instead of ffmpeg

### ISSUE THREAD

**Issue by AdrianEddy** [alichtman/gopro-chaptered-video-assembler#11]
Just letting you know that [mp4-merge](https://github.com/gyroflow/mp4-merge) exists and is much more portable and robust than ffmpeg (retains all possible tracks and metadata) and is available as a library

**Comment by alichtman** [comment]
Thanks. Using this library would allow the deletion of all of `ffmpeg.rs`, and would simplify the "merge videos" code a lot. I'd accept a PR making this change.

**Comment by draco1544** [comment]
Any news on that ?

**Comment by draco1544** [comment]
How i can use this version, because the latest release do not contain this change

**Comment by alichtman** [comment]
I'll make a new release when I get around to it. Or you can build and install it from source (something like `$ cargo install --path .`, but don't quote me). 

Why does this feature interest you so much? It should be roughly as efficient and performant as the ffmpeg solution.

It cleans up a bunch of complexity in the code, which is nice for me, but for you as an end-user, I don't really get the benefit

**Comment by AdrianEddy** [comment]
The benefit is that the gyro data is preserved, which is quite important for certain users

**Comment by alichtman** [comment]
What do you do with the gyro data on a GoPro? I was under the impression that you could, for example, set horizon lock *in camera* but not in post.

**Comment by AdrianEddy** [comment]
You can stabilize and set horizon lock in post, even if you're shooting with hypersmooth enabled in camera. The metadata also includes a lot of other things like GPS, temperature, shutter speed etc. Most common usage is to stabilize ([Reelsteady](https://gopro.com/en/us/info/gopro-player), [Gyroflow](https://gyroflow.xyz/)), and second most common is to add GPS or speed overlays ([telemetry-overlay](https://goprotelemetryextractor.com/telemetry-overlay-gps-video-sensors)).

ffmpeg discards the entire metadata, while mp4-merge preserves everything as is

**Comment by alichtman** [comment]
Thanks for the explanation. I'll cut a new release when I have a moment :)

**Comment by draco1544** [comment]
> Thanks for the explanation. I'll cut a new release when I have a moment :)

Any news ? Or what are the exact steps for me to build it ?

**Comment by alichtman** [comment]
v0.5.2 is available on crates.io: https://crates.io/crates/gopro-chaptered-video-assembler 

Please note the instructions for building the repo yourself in the README: https://github.com/alichtman/gopro-chaptered-video-assembler/tree/v0.5.2?tab=readme-ov-file#building-and-installing-source

**Comment by Routhinator** [comment]
```
   Compiling gopro-chaptered-video-assembler v0.5.2
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/routhinator/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/gopro-chaptered-video-assembler-0.5.2/src/main.rs:1:1
  |
1 | #![feature(path_file_prefix)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

The version that was pushed to crates.io seems to be bugged as it has a feature flag (? I think, not familiar with Rust) in the code.

**Comment by Routhinator** [comment]
```

Feature attributes are only allowed on the nightly release channel. Stable or beta compilers will not comply.

Erroneous code example:

#![feature(lang_items)] // error: `#![feature]` may not be used on the
                        //        stable release channel

If you need the feature, make sure to use a nightly release of the compiler (but be warned that the feature may be removed or altered in
the future).
```

**Comment by alichtman** [comment]
@Routhinator Like the error message suggests: you can compile this crate with a nightly rust compiler, but not a stable compiler. I can check to see if these features have made it to stable yet (so I can remove the feature flag and it would work with the stable compiler).

**Comment by Routhinator** [comment]
Yes I understand I can compile it, however I was following the project directions to install the stable version without need to compile from the Readme, and this error comes up from the version that was released to the carge stable channel. So the released package is broken, hence my bringing this up.

**Comment by alichtman** [comment]
Cargo doesn't have a concept of release channels, afaik. 

Try this solution for compiling this package from cargo using the nightly compiler build: https://stackoverflow.com/a/53137160

If that works for you, I'd gladly accept a PR mentioning this in the README.
